### ISSUE TITLE
Plugin dependencies

### ISSUE THREAD

**Issue by Xe** [shockkolate/arata#15]
This would be used for things like `Protocol.ElementalIRCd` importing the `Protocol.Charybdis` handlers for simplicity's sake.

**Comment by ori-sky** [comment]
This should already be possible with:

``` haskell
module Protocol.ElementalIRCd where

import qualified Protocol.Charybdis

exports = Protocol.Charybdis.exports
```

**Comment by Xe** [comment]
Oh, I see. I'll close this for reference.
