### ISSUE TITLE
Arata does not error out if no protocol module is loaded

### ISSUE THREAD

**Issue by Xe** [shockkolate/arata#17]
Repro steps:
1. Remove `Protocol.Charybdis` from the modules list.
2. Start Arata.

It will start the RegistrationAction but never do anything.

**Comment by ori-sky** [comment]
This is actually intentional. The default values of `fromProtocol` and `toProtocol` are `const (return [])` which is equivalent to `\_ -> return []`. The default behaviour of `makeUid` is to `return` the String equivalent of the Integer UID with `show`.

**Comment by ori-sky** [comment]
I'm going to add a warning to be displayed on load when no `ProtocolExport` is found.

**Comment by ori-sky** [comment]
This is resolved in a45a659bbceda145d2518bac550f88dd3080bbef.
