### ISSUE TITLE
Tidy up Command type

### ISSUE THREAD

**Issue by ori-sky** [shockkolate/arata#26]
The `Command` type currently holds records for all the help information associated with a command. This is not ideal as the help information is not directly associated with a command; it simply describes the command in a format usable by `module NickServ.Help`.

I intend to resolve this by giving `Command` a list of `Dynamic` values called **`extensions`**, allowing data of any type to be dynamically associated with a `Command` and to be retrieved in a type-safe way.

With respect to help information specifically, I will write a new `module Ext.Help` which exposes a type `ExtHelp` used to encapsulate only the help information. Each command module will import this extension module and export a value of this type with the `Command` they export. `module NickServ.Help` will also import the extension module and retrieve the `ExtHelp` value through the use of `fromDynamic`, which returns `Nothing` if the type check fails.

**Comment by Xe** [comment]
I think the Dynamic list of Extensions should be its own meta-issue.

**Comment by ori-sky** [comment]
I've determined that the type of `extensions` should be `Map TypeRep Dynamic`, meaning a map of `Dynamic` values keyed by type representations. This will allow for more efficient lookups of extensions than if using a list.

Also, @Xe, right now there is only one extension and the main focus of this issue is to resolve the clutter that currently exists in the `Command` type by introducing this concept of extensions into the code.
